import { useState } from "react";
// Showfonts component to display font options for users to add to the canvas
// eslint-disable-next-line react/prop-types
function Showfonts({ onFontClick }) {
  const [fonts] = useState([
    { name: "Arial", style: { fontFamily: "Arial" } },
    { name: "Courier", style: { fontFamily: "Courier" } },
    { name: "Georgia", style: { fontFamily: "Georgia" } },
    { name: "Times New Roman", style: { fontFamily: "Times New Roman" } },
    { name: "Verdana", style: { fontFamily: "Verdana" } },
    { name: "Tahoma", style: { fontFamily: "Tahoma" } },
    { name: "Trebuchet MS", style: { fontFamily: "Trebuchet MS" } },
    { name: "Comic Sans MS", style: { fontFamily: "Comic Sans MS" } },
    { name: "Impact", style: { fontFamily: "Impact" } },
    { name: "Lucida Console", style: { fontFamily: "Lucida Console" } },
    { name: "Palatino Linotype", style: { fontFamily: "Palatino Linotype" } },
    { name: "Arial Black", style: { fontFamily: "Arial Black" } },
    { name: "Garamond", style: { fontFamily: "Garamond" } },
    { name: "Bookman", style: { fontFamily: "Bookman" } },
    { name: "Century Gothic", style: { fontFamily: "Century Gothic" } },
    { name: "Segoe UI", style: { fontFamily: "Segoe UI" } },
    { name: "Frank Ruhl Libre", style: { fontFamily: "Frank Ruhl Libre" } },
    { name: "Futura", style: { fontFamily: "Futura" } },
    { name: "Baskerville", style: { fontFamily: "Baskerville" } },
    { name: "Optima", style: { fontFamily: "Optima" } },
    { name: "Bodoni", style: { fontFamily: "Bodoni" } },
    { name: "Didot", style: { fontFamily: "Didot" } },
    { name: "Rockwell", style: { fontFamily: "Rockwell" } },
    { name: "Arial Narrow", style: { fontFamily: "Arial Narrow" } },
    { name: "Helvetica", style: { fontFamily: "Helvetica" } },
    { name: "Myriad Pro", style: { fontFamily: "Myriad Pro" } },
    { name: "Gill Sans", style: { fontFamily: "Gill Sans" } },
    { name: "Avenir", style: { fontFamily: "Avenir" } },
    { name: "Source Sans Pro", style: { fontFamily: "Source Sans Pro" } },
    { name: "Roboto", style: { fontFamily: "Roboto" } },
    { name: "Open Sans", style: { fontFamily: "Open Sans" } },
    { name: "Lato", style: { fontFamily: "Lato" } },
    { name: "Montserrat", style: { fontFamily: "Montserrat" } },
    { name: "Raleway", style: { fontFamily: "Raleway" } },
    { name: "Oswald", style: { fontFamily: "Oswald" } },
    { name: "Poppins", style: { fontFamily: "Poppins" } },
    { name: "Noto Sans", style: { fontFamily: "Noto Sans" } },
    { name: "Ubuntu", style: { fontFamily: "Ubuntu" } },
    { name: "Merriweather", style: { fontFamily: "Merriweather" } },
    { name: "PT Sans", style: { fontFamily: "PT Sans" } },
    { name: "Droid Sans", style: { fontFamily: "Droid Sans" } },
    { name: "Playfair Display", style: { fontFamily: "Playfair Display" } },
    { name: "Quicksand", style: { fontFamily: "Quicksand" } },
    { name: "Cabin", style: { fontFamily: "Cabin" } },
    { name: "Inconsolata", style: { fontFamily: "Inconsolata" } },
    { name: "Exo", style: { fontFamily: "Exo" } },
    { name: "Titillium Web", style: { fontFamily: "Titillium Web" } },
    { name: "Zilla Slab", style: { fontFamily: "Zilla Slab" } },
    { name: "Coda", style: { fontFamily: "Coda" } },
    { name: "Righteous", style: { fontFamily: "Righteous" } },
    { name: "Satisfy", style: { fontFamily: "Satisfy" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Pacifico", style: { fontFamily: "Pacifico" } },
    { name: "Lobster", style: { fontFamily: "Lobster" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Satisfy", style: { fontFamily: "Satisfy" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
    { name: "Rochester", style: { fontFamily: "Rochester" } },
    { name: "Srisakdi", style: { fontFamily: "Srisakdi" } },
    { name: "Niconne", style: { fontFamily: "Niconne" } },
    { name: "Dancing Script", style: { fontFamily: "Dancing Script" } },
    { name: "Sacramento", style: { fontFamily: "Sacramento" } },
    { name: "Great Vibes", style: { fontFamily: "Great Vibes" } },
    { name: "Allura", style: { fontFamily: "Allura" } },
    { name: "Cookie", style: { fontFamily: "Cookie" } },
    { name: "Pinyon Script", style: { fontFamily: "Pinyon Script" } },
    { name: "Rock Salt", style: { fontFamily: "Rock Salt" } },
  ]);

  return (
    <div className="w-full">
      <div className="pannel-title text-center">
        <h1>Fonts</h1>
      </div>
      <div className="font-map w-full flex flex-col gap-2 px-2">
        {fonts.map((font, index) => (
          <div
            key={index}
            className="bg-background2 rounded-lg p-2 cursor-pointer"
            style={{
              ...font.style,
            }}
            onClick={() => onFontClick(font)}
          >
            {font.name}
          </div>
        ))}
      </div>
    </div>
  );
}

export default Showfonts;
