import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Auto social",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      className="dark bg-background text-text w-screen h-full flex flex-col justify-center items-center"
      lang="en"
    >
      <body
        className={`${geistSans.variable} flex flex-col justify-center items-center w-full ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
